name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  args:
    description: 'Script arguments, usage in src/README.txt'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
